/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRoute
  '/scores': typeof ScoresRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/teacher': typeof TeacherRoute
  '/teachers': typeof TeachersRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRoute
  '/scores': typeof ScoresRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/teacher': typeof TeacherRoute
  '/teachers': typeof TeachersRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRoute
  '/scores': typeof ScoresRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/teacher': typeof TeacherRoute
  '/teachers': typeof TeachersRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/reports'
    | '/results'
    | '/scores'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/teacher'
    | '/teachers'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/reports'
    | '/results'
    | '/scores'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/teacher'
    | '/teachers'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/reports'
    | '/results'
    | '/scores'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/teacher'
    | '/teachers'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  AttendanceRoute: typeof AttendanceRoute
  ClassesRoute: typeof ClassesRoute
  DashboardRoute: typeof DashboardRoute
  ReportsRoute: typeof ReportsRoute
  ResultsRoute: typeof ResultsRoute
  ScoresRoute: typeof ScoresRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRoute
  SubjectsRoute: typeof SubjectsRoute
  TeacherRoute: typeof TeacherRoute
  TeachersRoute: typeof TeachersRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  AttendanceRoute: AttendanceRoute,
  ClassesRoute: ClassesRoute,
  DashboardRoute: DashboardRoute,
  ReportsRoute: ReportsRoute,
  ResultsRoute: ResultsRoute,
  ScoresRoute: ScoresRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRoute,
  SubjectsRoute: SubjectsRoute,
  TeacherRoute: TeacherRoute,
  TeachersRoute: TeachersRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
